str = ''
str = '<div class="gnb">'
str +='   <ul class="gnb_site_map_wrap">'
str +='      <li>'
str +='         <button type="button" class="site_map">사이트맵</button>'
str +='         <div class="site_map_con">'
str +='            <button type="button" class="site_map_close">사이트맵 닫기</button>'
str +='            <p>사이트맵</p>'
str +='         </div>'
str +='      </li>'
str +='    </ul>'
str +='   <ul class="gnb_menu_wrap">'
str +='      <li>'
str +='         <a href="" class="m_working_time">출퇴근 조회</a>'
str +='         <ul>'
str +='            <li><span>출퇴근 조회</span></li>'
str +='            <li><a href="qr_make.html">출퇴근 QR코드 생성</a></li>'
str +='            <li><a href="go_work.html">출퇴근기록관리</a></li>'
str +='            <li><a href="work_status.html">출퇴근현황</a></li>'
str +='         </ul>'
str +='      </li>'
str +='      <li class="">'
str +='         <a href="" class="m_hr">인사관리</a>'
str +='         <ul>'
str +='            <li><span>인사관리</span></li>'
str +='            <li><a href="hr_m.html">인사관리</a></li>'
str +='            <li><a href="depart_m.html">부서관리</a></li>'
str +='            <li><a href="customer.html">거래처관리</a></li>'
str +='            <li><a href="project_m.html">프로젝트관리</a></li>'
str +='            <li><a href="annual_r.html">연차기초등록</a></li>'
str +='            <li><a href="annual_s.html">연차현황관리</a></li>'
str +='            <li><a href="payment_r.html">결재라인등록</a></li>'
str +='         </ul>'
str +='      </li>'
str +='      <li>'
str +='         <a href="" class="m_salary">급여관리</a>'
str +='         <ul>'
str +='            <li><span>급여관리</span></li>'
str +='            <li><a href="salary_save.html">급여저장</a></li>'
str +='            <li><a href="salary.html">급여명세서</a></li>'
str +='         </ul>'
str +='       </li>'
str +='      <li>'
str +='         <a href="" class="m_report">주간보고서</a>'
str +='         <ul>'
str +='            <li><span>주간보고서</span></li>'
str +='            <li><a href="report_r.html">주간보고서 등록</a></li>'
str +='            <li><a href="report_a.html">주간보고서 승인</a></li>'
str +='         </ul>'
str +='      </li>'
str +='      <li>'
str +='         <a href="" class="m_business">출장/휴가관리</a>'
str +='         <ul>'
str +='            <li><span>출장/휴가관리</span></li>'
str +='            <li><a href="individual_m.html">개인별 연차관리</a></li>'
str +='            <li><a href="business_r.html">출장/휴가등록</a></li>'
str +='            <li><a href="business_a.html">출장/휴가승인</a></li>'
str +='            <li><a href="vehicle_r.html">차량유지비 등록</a></li>'
str +='            <li><a href="vehicle_a.html">차량유지비 승인</a></li>'
str +='            <li><a href="travel_r.html">출장비신청 등록</a></li>'
str +='            <li><a href="travel_a.html">출장비신청 승인</a></li>'
str +='            <li><a href="spending_r.html">지출결의서 등록</a></li>'
str +='            <li><a href="spending_a.html">지출결의서 승인</a></li>'
str +='         </ul>'
str +='      </li>'
str +='      <li>'
str +='         <a href="" class="m_notice">공지사항</a>'
str +='         <ul>'
str +='            <li><span>공지사항</span></li>'
str +='            <li><a href="notice.html">공지사항</a></li>'
str +='         </ul>'
str +='      </li>'
str +='      <li>'
str +='         <a href="" class="m_data">자료실</a>'
str +='         <ul>'
str +='            <li><span>자료실</span></li>'
str +='            <li><a href="data.html">자료실</a></li>'
str +='         </ul>'
str +='      </li>'
str +='      <li>'
str +='         <a href="" class="m_user">사용자설정</a>'
str +='         <ul>'
str +='            <li><span>사용자설정</span></li>'
str +='            <li><a href="personal_r.html">개인결재라인등록</a></li>'
str +='         </ul>'
str +='      </li>'
str +='      <li>'
str +='         <a href="" class="m_system">시스템관리</a>'
str +='         <ul>'
str +='            <li><span>시스템관리</span></li>'
str +='            <li><a href="menu_list.html">메뉴목록</a></li>'
str +='            <li><a href="menu_auth.html">메뉴 권한</a></li>'
str +='            <li><a href="common_code.html">공통코드</a></li>'
str +='            <li><a href="schedule.html">일정관리</a></li>'
str +='         </ul>'
str +='      </li>'
str +='   </ul>'
str +='</div>'

document.write( str );